In [1]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')
import numpy as np

In [2]:
A = np.random.rand(4,4)
print(A)

print(A[:,-1].var(axis=0))
print(A[:,-1].mean(axis=0))

[[0.75555762 0.30432313 0.1568058  0.86260687]
 [0.17219219 0.12143133 0.75627432 0.33488859]
 [0.73385355 0.50494686 0.50369951 0.93922073]
 [0.95734273 0.01756843 0.05437694 0.92052654]]
0.06226560007673005
0.7643106843707294


# MPS

In [4]:
# 10 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_10bd.npy")
TEST = np.load("mps/20x_mps_testloss_10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_20bd.npy")
TEST = np.load("mps/20x_mps_testloss_20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_40bd.npy")
TEST = np.load("mps/20x_mps_testloss_40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

10
0.897165
0.00013383927499999992

20
0.9108750000000002
0.0001289998750000001

40
0.91476
8.15013999999999e-05



# FC to MPS

In [12]:
# 10 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_10bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_20bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_40bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

10
0.5407099999999999
9.503989999999998e-05

20
0.5501699999999999
9.326409999999986e-05

40
0.5558850000000001
5.996927499999985e-05



# CNN to MPS

In [9]:
# 10 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss10bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss20bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss40bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

10
0.9056450000000001
8.492547499999994e-05

20
0.924215
6.765827499999991e-05

40
0.9405899999999999
4.381590000000007e-05

