In [6]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')
import numpy as np

In [7]:
A = np.random.rand(4,4)
print(A)

print(A[:,-1].var(axis=0))
print(A[:,-1].mean(axis=0))

[[0.45501731 0.28849568 0.45742992 0.02567647]
 [0.35728739 0.4219454  0.850416   0.16976766]
 [0.31108401 0.35614053 0.5169388  0.422134  ]
 [0.24834971 0.27433653 0.88997003 0.21854856]]
0.020165991782731707
0.20903167121018468


# MPS

In [8]:
# 10 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_10bd.npy")
TEST = np.load("mps/20x_mps_testloss_10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_20bd.npy")
TEST = np.load("mps/20x_mps_testloss_20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_40bd.npy")
TEST = np.load("mps/20x_mps_testloss_40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))

# 80 bond dimensions
TRAIN = np.load("mps/20x_mps_trainloss_80bd.npy")
TEST = np.load("mps/20x_mps_testloss_80bd.npy")

print(80)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

10
0.897165
0.00013383927499999992

20
0.9108750000000002
0.0001289998750000001

40
0.91476
8.15013999999999e-05
80
0.9161349999999999
0.00031344027500000016



# FC to MPS

In [9]:
# 10 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_10bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_20bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("fc_to_mps/20x_fc_to_mps_trainloss_40bd.npy")
TEST = np.load("fc_to_mps/20x_fc_to_mps_testloss_40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 80 bond dimensions


10
0.5407099999999999
9.503989999999998e-05

20
0.5501699999999999
9.326409999999986e-05

40
0.5558850000000001
5.996927499999985e-05



# CNN to MPS

In [10]:
# 10 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss10bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss20bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss40bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 80 bond dimensions
TRAIN = np.load("cnn_to_mps/20x_cnn_to_mps_trainloss80bd.npy")
TEST = np.load("cnn_to_mps/20x_cnn_to_mps_testloss80bd.npy")

print(80)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

10
0.9056450000000001
8.492547499999994e-05

20
0.924215
6.765827499999991e-05

40
0.9405899999999999
4.381590000000007e-05

80
0.9439799999999998
7.354659999999998e-05

