In [1]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')
import numpy as np

In [2]:
A = np.random.rand(4,4)
print(A)

print(A[:,-1].var(axis=0))
print(A[:,-1].mean(axis=0))

[[0.71064216 0.82005172 0.23216716 0.911615  ]
 [0.52696333 0.1242924  0.39256846 0.41993459]
 [0.98499723 0.72094026 0.60700694 0.95434655]
 [0.71106255 0.54071343 0.46242993 0.14659534]]
0.11510020055573406
0.6081228689147565


# MPS

In [7]:
# 10 bond dimensions
TRAIN = np.load("20x_mps_trainloss_10bd.npy")
TEST = np.load("20x_mps_testloss_10bd.npy")

print(10)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 20 bond dimensions
TRAIN = np.load("20x_mps_trainloss_20bd.npy")
TEST = np.load("20x_mps_testloss_20bd.npy")

print(20)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

# 40 bond dimensions
TRAIN = np.load("20x_mps_trainloss_40bd.npy")
TEST = np.load("20x_mps_testloss_40bd.npy")

print(40)
print(TEST[:,-1].mean(axis=0))
print(TEST[:,-1].var(axis=0))
print()

0.897165
0.00013383927499999992


# FC TO MPS

The fc has an accuracy of 
Test loss:  [0.205, 0.26762, 0.34435, 0.45653, 0.50299, 0.48948, 0.56028, 0.54766, 0.59326, 0.6071, 0.59979, 0.62026, 0.60682, 0.63139, 0.62401, 0.62037, 0.62014, 0.60877, 0.62892, 0.62471, 0.62431, 0.63479, 0.62603, 0.62664, 0.62532]